version: '3.9'

services:
      #- MONGO_URL=mongodb://blogusr:blogpwd@mongo:27016/blogs
      #- IMAGE_SERVER_URL=http://localhost:8888
      #- IMAGE_SERVER_SECURITY_KEY=MY_SECURE_KEY

  thumbor:
    image: thumbororg/thumbor:7.7.3-py-3.11
    volumes:
      - ./images:/data:Z
      - ./thumbor_config/thumbor.conf:/etc/thumbor.conf:ro
    ports:
      - "8888:8888"
    networks:
      - app

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DB:-mongodb}
      BLOG_USER: ${BLOG_USER:-blogusr}
      BLOG_PASSWORD: ${BLOG_PASSWORD:-blogpw}
    volumes:
      - ./mongo-data:/data/db:Z
      - ./mongo-log:/var/log/mongodb:Z
      - ./docker/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./docker/seeding:/docker/seeding
    networks:
      - app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT:-mongodb}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT:-mongodb}:${MONGO_ROOT_PASSWORD:-mongodb}@mongo:27017/
    networks:
      - app

volumes:
  cache:
    driver: local
networks:
  app:
    driver: bridge